### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by martinandersen3d** [MatheusrdSantos/vue-quick-chat#14]
I've tried to change the text color. But I think this one is overriding the text color?

https://github.com/MatheusrdSantos/vue-quick-chat/blob/e6009932e30693fa6c9815090d423de1cb1c92ca/src/components/MessageDisplay.vue#L139

Here is my colors:

```   

colors:{
        header:{
          bg: '#0099ff',
          text: '#fff'
        },
        message:{
          myself: {
            bg: '#0099ff',
            text: '#fff'
          },
          others: {
            bg: '#f1f0f0',
            text: '#3e3e3e'
          },
          messagesDisplay: {
            bg: '#fff'
          }
        },
```

text colors, should be: other=black, and myself=white

![s](https://user-images.githubusercontent.com/19984581/68416150-2a054f00-0194-11ea-9fe4-db52507e44be.png)

**Comment by MatheusrdSantos** [comment]
Hi, @martinandersen3d!
Thanks, for your report. I really forgot to implement that functionality.
However, @Tofandel solved this issue here: 5b0312873dae261da402b4c60eb7fe560946e5e2
Now you just have to update the npm package to version 1.0.3
