### ISSUE TITLE
[Bug] IOS - Keyboard "Done/Submit" button

### ISSUE THREAD

**Issue by martinandersen3d** [MatheusrdSantos/vue-quick-chat#18]
IOS only.
Works fine in Safari, Chrome etc.
----
I'm not going to use so much time on this one...

Description:
- Clicking **Done** does nothing.
- Clicking the **Red Triangle** works.

Possible solutions:
```
- Inspecting the DOM, it looks like there is not used a <input type="text"> and a <input type="submit" value="Submit">. I'm not sure if that will fix it.. 
- Having a <form onsubmit="myFunction()">...</form> around the text field is maybe a solution.. 
```

Anyway, its a smaller thing, now documented :-)

![iOGYK3y4wY](https://user-images.githubusercontent.com/19984581/68997254-9ecb3e00-08a4-11ea-95dd-c1297ec18ff6.gif)

**Comment by MatheusrdSantos** [comment]
Maybe this problem is happening because I'm using a div with `contenteditable="true"` as input text. So the keyboard doesn't detect any input field to submit the text.

I'll solve this issue in the next few days.
Thanks for reporting this error.

**Comment by martinandersen3d** [comment]
OK, I did try some different combinations here. Whatever I try it always says "Done".
Its a "bug" on apples side, **and not something we can change.**

Good answer from stackoverflow:
> As of iOS 9.3 this is not possible. (Unlike android) iOS is not open source so it's hard to prove but It's likely intentional because there is no other safe way to exit the keyboard. (Unlike android which has a back/close-keyboard button on swipe up or physically depending on the device).
https://stackoverflow.com/questions/19939487/ios-keyboard-without-prev-next-done-button-for-html-input-field



![image](https://user-images.githubusercontent.com/19984581/69000341-4f9a0300-08ce-11ea-9b72-af7f5361cd1d.png)

some quick and dirty code:
https://codepen.io/martinandersen3d/pen/KKKrLOj

**Comment by MatheusrdSantos** [comment]
Great! So this is the default IOS behavior.
