### ISSUE TITLE
feather v-icon has a conflict with vuetifyjs v-icon

### ISSUE THREAD

**Issue by Qanah** [MatheusrdSantos/vue-quick-chat#19]
First I need to thank you for this component it's very useful, Please change the feather v-icon name in `vue-quick-chat/src/index.js` line 4 because thair is a conflict with vuetifyjs

**Comment by MatheusrdSantos** [comment]
Hi, @Qanah! Thanks for your feedback.
I'll change the name as soon as possible.

**Comment by MatheusrdSantos** [comment]
Solved here d6844015b4e38e4cc07143057f2d421805efb83a
