### ISSUE TITLE
delete the header

### ISSUE THREAD

**Issue by iseesaw** [MatheusrdSantos/vue-quick-chat#26]
I don't want to have the header, how can I delete it?
Thank you.

**Comment by MatheusrdSantos** [comment]
There's no way to remove the header. However, it's an easy feature to implement, so I'll release it tomorrow.

**Comment by iseesaw** [comment]
Thank you for your reply.
I implements it by setting the height of the header zero.

**Comment by MatheusrdSantos** [comment]
@iseesaw this functionality is available now #27

**Comment by iseesaw** [comment]
> @iseesaw this functionality is available now #27
> Just update to version 1.0.9

Ok，thank you very much！
