### ISSUE TITLE
on close props is function 

### ISSUE THREAD

**Issue by ahmedabdel3al** [MatheusrdSantos/vue-quick-chat#30]
onClose props is function so if i need to pass param to this function this method 
will fire when component mounted so the chat will be close again 
so i suggesting to be event
and we catch this event outside component

current  ` :on-close="onClose(pram)"`
suggest `@onClose="onClose(param)"`

**Comment by MatheusrdSantos** [comment]
Hi, @ahmedabdel3al. I'll fix it as soon as possible.

**Comment by MatheusrdSantos** [comment]
Hi, @ahmedabdel3al. It's now solved. Just update to version 1.2.0.
