### ISSUE TITLE
Feature: Include href links inside text messages

### ISSUE THREAD

**Issue by smileypop** [MatheusrdSantos/vue-quick-chat#36]
Can you add support for auto parsing of links included inside text messages? Something like this:

> Hey check out this cool website [www.vuejs.org](www.vuejs.org)

**Comment by MatheusrdSantos** [comment]
Hi, @smileypop!
That's a good idea. I'll implement it as soon as possible.

Thanks

**Comment by MatheusrdSantos** [comment]
Implemented here 0265b64cdf7d647277a88f83d0736ebcbd47843b. I'll release it soon.

**Comment by MatheusrdSantos** [comment]
Just update to version 1.2.3 and check the docs. I added the linkOptions prop to configure the links inside of the messages.

Thanks, for your suggestion.

**Comment by smileypop** [comment]
@MatheusrdSantos thank you!
