### ISSUE TITLE
header participants text. and maximum height.

### ISSUE THREAD

**Issue by AbingLeopoldo** [MatheusrdSantos/vue-quick-chat#39]
Thanks for the greate project,. Is their an option to maximize the hight of messages display (in "quick-chat-container" class),? and to hide the participants header text (in "header-paticipants-text" class)?.

**Comment by MatheusrdSantos** [comment]
Hi, @AbingLeopoldo!
About your first question, what do you mean by 'maximize the height of message display'?
The message display is already configured to grows according to its parent's height. So, if you need to make it grows, just change the height of the chat parent.
About you second question, you can change the behavior of the header using slots (check this section [usage](https://github.com/MatheusrdSantos/vue-quick-chat#usage))
``` javascript
<Chat>
    <template v-slot:header>
        // Here you can add any code that will appears on the header, even an empty element
        <div>
        </div>
    </template>
</Chat>
```
Thanks for your feedback.
