### ISSUE TITLE
Typing

### ISSUE THREAD

**Issue by bekee** [MatheusrdSantos/vue-quick-chat#43]
How can I implement typing effect with the component?

**Comment by MatheusrdSantos** [comment]
Hi, @bekee. Could you explain better what you need?

**Comment by bekee** [comment]
When a user is typing a  message, I want to use the whisper function in laravel-echo to tell the receiver that the other person. literally I was hoping there could be a slot on the message display area.

**Comment by MatheusrdSantos** [comment]
Currently, the chat doesn't support this feature yet. But it's a good feature to implement.

I'll implement it when I get some free time.
Fell free to create a PR if you really need this feature quickly.

Thanks, @bekee.
