### ISSUE TITLE
Proposal: Make scrolling work and keep chatbox fixed irrespective of scroll position

### ISSUE THREAD

**Issue by Mnshah219** [MatheusrdSantos/vue-quick-chat#44]
Hello, 
Currently when we use this component the inner scroll does not work, when we scroll, the scrollbar of main windows is the one that is getting scrolled, so it would be nice if innerscroll could made to work or remove it from ui altogether, also scrollBottom:{messageSent:true} only makes sense if we could type in message irrespective of scroll position

![Capture](https://user-images.githubusercontent.com/35868664/95552298-1577a980-0a2a-11eb-9e79-fabd04aed4b1.PNG)

**Comment by jhonveramendi** [comment]
Hi,
<div style="height: 500px;" class="w-full">
                    <Chat :participants="particip...
 </div>
I solved it like this...

it's a shame not to have answered you before

**Comment by jhonveramendi** [comment]
<div style="height: 500px;" class="w-full">
                    <Chat :participants="particip...
</div>
it's a shame not to have answered you before

**Comment by MatheusrdSantos** [comment]
Hi, @Mnshah219! Sorry for my late response. I didn't get notified by GitHub. To enable the inner scroll you should set a max-width to the chat parent element.

**Comment by reBiocoder** [comment]
> 

thx,this is good job!
