### ISSUE TITLE
Pushing messages causes the timestamp on all previous messages to be set to the current time

### ISSUE THREAD

**Issue by sgarringer** [MatheusrdSantos/vue-quick-chat#50]
I'm having trouble using this to build a chat app.

Steps to reproduce:

Add a single message to this.messages

Create a second message, and call this.messages.push(secondmessage)

The timestamp on the previous message will be sent to the current time.

Rolling back to 1.2.6 resolved issue.  It seems to be related to commit 18f60fbced885919da937747ca118aa2b25fd077

**Comment by MatheusrdSantos** [comment]
Hi, @sgarringer. It was my mistake on this commit 18f60fb. I already know how to solve it. I'll release a new version today.

Thank you!

**Comment by MatheusrdSantos** [comment]
Fixed on version 1.2.8.

Thanks again!
