### ISSUE TITLE
Incorrect rendering in Firefox

### ISSUE THREAD

**Issue by bontibon** [MatheusrdSantos/vue-quick-chat#8]
Firefox: 69.0.2
vue-quick-chat: 1.0.1

Screenshot:
![image](https://user-images.githubusercontent.com/110883/67287637-1756fe80-f4a1-11e9-8530-48a004735403.png)

The component is rendered correctly if I toggle off the `height: 100%` style from `.message-text > p[data-v-0e9711a6]`:
![image](https://user-images.githubusercontent.com/110883/67287773-4ec5ab00-f4a1-11e9-85bb-7ac468b162c6.png)

**Comment by MatheusrdSantos** [comment]
Hi, @bontibon! Thanks for your feedback.
I'll solve this issue in the next few days.

**Comment by MatheusrdSantos** [comment]
Hi, @bontibon. 
I fixed this issue here #10, so I'll close it. 
Thanks again.
